version: '3.8'

services:
  redis:
    image: "redis:6"
    container_name: "redis-container"
    ports:
      - "6379:6379"
    networks:
      - app-network

  flask-app:
    build: .
    container_name: "flask-app"
    ports:
      - "5000:5000"
    depends_on:
      - redis
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
